name: ${project.name}
version: ${project.version}-${env.BUILD_NUMBER}
description: ${project.description}
author: ${pluginyml.author}
main: ${bukkit.pluginyml.main}
load: STARTUP

commands:
    jsonmessagemaker:
        description: Send messages with hover and click effects.
        aliases: [jmm, jmsg]
        permission: jsonmessagemaker.command
